# .github/workflows/ci.yml
name: Reusable CI Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm dependencies
        working-directory: ./ClientApp
        run: npm install

      - name: Build npm project
        working-directory: ./ClientApp
        run: npm run build

      - name: Publish .NET Core application
        run: dotnet publish -c Release -o ./publish

      - name: Echo Hello World
        run: echo "Hello, World!"
